#!/usr/bin/env bash
set -e

psql -v -U postgres -d "$POSTGRES_DB" -c "CREATE USER $POSTGRES_DB_USERNAME WITH PASSWORD '$POSTGRES_DB_PASSWORD';"
psql -v -U postgres -d "$POSTGRES_DB" -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_DB_USERNAME;"
psql -v -U postgres -d "$POSTGRES_DB" -c "GRANT USAGE, CREATE ON SCHEMA public TO $POSTGRES_DB_USERNAME;"
