services:
  compose-docs:
    image: tons/docker-compose-docs:2.1.0
    volumes:
      - ../../:/src:ro
    environment:
      DOCKER_COMPOSE_FILE_GLOBS: /src/docker-compose.yml;/src/overlays/*/docker-compose.yml
    network_mode: none
