PRE_COMMIT_VERSION ?= 4.3.0

# PROJECT_NAME: unique name for this instance (e.g. dev, test, prod).
# Env file is always instances/$(PROJECT_NAME).env — generated by scripts/generate-env.sh.
PROJECT_NAME ?= $(notdir $(CURDIR))
ENV_FILE = instances/$(PROJECT_NAME).env
BACKUP_DIR ?= ./backups/$(PROJECT_NAME)

.PHONY: init playwright test reinit check backup-database backup-file-storage backup restore-database restore-file-storage restore docs generate-stack-envs create-instance launch-postgres launch-instance launch-traefik launch-monitoring ensure-networks stop-instance clean clean-all config get-backup-timestamp

init:
	@test -d .venv || python3 -m venv .venv
	.venv/bin/python -m pip install "pre-commit==$(PRE_COMMIT_VERSION)"
	.venv/bin/pre-commit install

playwright: init
	.venv/bin/python -m pip install playwright pytest pytest-playwright pytest-order requests pydantic
	.venv/bin/playwright install

test: playwright
	DEBUG=pw:api .venv/bin/pytest --capture=no --exitfirst

test-ui: playwright
	DEBUG=pw:api .venv/bin/pytest --headed --capture=no --exitfirst

reinit:
	rm -rf .venv
	$(MAKE) init

# Generate .env files for stacks/traefik/ and stacks/monitoring/ (run once per server).
# Requires: GEN_LETSENCRYPT_ACME_EMAIL and GEN_GRAFANA_HOSTNAME to be set.
# Example: GEN_LETSENCRYPT_ACME_EMAIL=ops@example.com GEN_GRAFANA_HOSTNAME=grafana.example.com make generate-stack-envs
generate-stack-envs:
	GEN_LETSENCRYPT_ACME_EMAIL=$(GEN_LETSENCRYPT_ACME_EMAIL) \
	GEN_GRAFANA_HOSTNAME=$(GEN_GRAFANA_HOSTNAME) \
		./scripts/generate-stack-envs.sh

install-loki-driver:
	docker plugin ls --format '{{.Name}}' | grep -q 'loki:latest' || ./scripts/install-loki-driver.sh
	docker plugin ls

check:
	.venv/bin/pre-commit run --all-files

BACKUP_TIMESTAMP ?= $(shell date -u +%Y-%m-%d_%H-%M-%S_%Z)

POSTGRES_COMPOSE_CMD = docker compose \
	--project-name $(PROJECT_NAME) \
	--env-file $(ENV_FILE) \
	-f stacks/postgres/docker-compose.yml

BACKUP_COMPOSE_CMD = BACKUP_DIR=$(BACKUP_DIR) docker compose \
	--project-name $(PROJECT_NAME) \
	--env-file $(ENV_FILE) \
	-f docker-compose.yml \
	-f stacks/backup/docker-compose.yml

get-backup-timestamp:
	@echo $(BACKUP_TIMESTAMP)

backup-database:
	mkdir -p $(BACKUP_DIR)
	$(BACKUP_COMPOSE_CMD) run -e BACKUP_TIMESTAMP=$(BACKUP_TIMESTAMP) --rm backup-database

backup-file-storage:
	mkdir -p $(BACKUP_DIR)
	$(BACKUP_COMPOSE_CMD) run -e BACKUP_TIMESTAMP=$(BACKUP_TIMESTAMP) --rm backup-file-storage

backup: backup-database backup-file-storage

restore-database:
	$(BACKUP_COMPOSE_CMD) stop app
	$(BACKUP_COMPOSE_CMD) run --rm restore-database
	$(BACKUP_COMPOSE_CMD) start app

restore-file-storage:
	$(BACKUP_COMPOSE_CMD) stop app
	$(BACKUP_COMPOSE_CMD) run --rm restore-file-storage
	$(BACKUP_COMPOSE_CMD) start app

restore:
	$(BACKUP_COMPOSE_CMD) stop app
	$(BACKUP_COMPOSE_CMD) run --rm restore-database
	$(BACKUP_COMPOSE_CMD) run --rm restore-file-storage
	$(BACKUP_COMPOSE_CMD) start app

docs:
	mkdir -p ./docs
	docker compose -f stacks/docs/docker-compose.yml run --rm compose-docs > docs/environment-variables.md

COMPOSE_CMD = docker compose \
	--project-name $(PROJECT_NAME) \
	--env-file $(ENV_FILE) \
	-f docker-compose.yml \
	-f overlays/profiling/docker-compose.yml \
	-f overlays/glowroot/docker-compose.yml

# Create the shared Docker networks required by the multi-instance workflow.
# Safe to run multiple times (ignores errors if networks already exist).
ensure-networks:
	docker network create proxy 2>/dev/null || true
	docker network create monitoring_net 2>/dev/null || true

# Start the standalone Traefik gateway (run once; watches stacks/traefik/conf.d/ for route changes)
launch-traefik: ensure-networks
	docker compose -f stacks/traefik/docker-compose.yml --env-file stacks/traefik/.env up $(COMPOSE_OPTS)

# Start the standalone monitoring stack (run once; watches stacks/monitoring/targets/ for new instances)
launch-monitoring: ensure-networks
	GRAFANA_HOSTNAME=$$(grep -E '^GRAFANA_HOSTNAME=' stacks/monitoring/.env | cut -d= -f2-) \
		envsubst < stacks/traefik/conf.d/monitoring.yml.template > stacks/traefik/conf.d/monitoring.yml
	docker compose -f stacks/monitoring/docker-compose.yml --env-file stacks/monitoring/.env up $(COMPOSE_OPTS)

# Generate the env file for a new instance.
# Example: APP_HOSTNAME=dhis2.example.com PROJECT_NAME=prod make create-instance
create-instance:
	@test -n "$(APP_HOSTNAME)" || (echo "Error: APP_HOSTNAME must be set" >&2; exit 1)
	GEN_PROJECT_NAME=$(PROJECT_NAME) GEN_APP_HOSTNAME=$(APP_HOSTNAME) ./scripts/generate-env.sh

# Start the PostgreSQL stack for a named instance.
# Creates a per-instance db network (PROJECT_NAME-db) and waits until healthy.
launch-postgres:
	docker network create $(PROJECT_NAME)-db 2>/dev/null || true
	$(POSTGRES_COMPOSE_CMD) up --wait -d

# Launch a named DHIS2 instance connected to the standalone Traefik, monitoring, and postgres stacks.
# Requires: PROJECT_NAME and ENV_FILE to be set, ensure-networks and launch-traefik and
#           launch-monitoring to have been run first.
# Example: PROJECT_NAME=dev ENV_FILE=instances/dev.env make launch-instance
launch-instance: ensure-networks install-loki-driver launch-postgres
	PROJECT_NAME=$(PROJECT_NAME) APP_HOSTNAME=$$(grep -E '^APP_HOSTNAME=' $(ENV_FILE) | cut -d= -f2-) \
		envsubst < stacks/traefik/conf.d/instance.yml.template > stacks/traefik/conf.d/$(PROJECT_NAME).yml
	PROJECT_NAME=$(PROJECT_NAME) \
		envsubst < stacks/monitoring/targets/dhis2/instance.json.template > stacks/monitoring/targets/dhis2/$(PROJECT_NAME).json
	PROJECT_NAME=$(PROJECT_NAME) \
		envsubst < stacks/monitoring/targets/postgres/instance.json.template > stacks/monitoring/targets/postgres/$(PROJECT_NAME).json
	$(COMPOSE_CMD) up $(COMPOSE_OPTS)

# Stop a named DHIS2 instance and remove its Traefik routes and Prometheus targets.
# Example: PROJECT_NAME=dev ENV_FILE=instances/dev.env make stop-instance
stop-instance:
	$(COMPOSE_CMD) down --remove-orphans
	$(POSTGRES_COMPOSE_CMD) down
	docker network rm $(PROJECT_NAME)-db 2>/dev/null || true
	rm -f stacks/traefik/conf.d/$(PROJECT_NAME).yml
	rm -f stacks/monitoring/targets/dhis2/$(PROJECT_NAME).json
	rm -f stacks/monitoring/targets/postgres/$(PROJECT_NAME).json

clean:
	$(COMPOSE_CMD) down --remove-orphans

clean-all:
	@if [ -t 0 ]; then \
		echo "WARNING: This will destroy all Docker volumes (database, file storage, monitoring data, etc.)."; \
		echo "This action is irreversible."; \
		read -p "Are you sure? [y/N] " confirm && [ "$$confirm" = "y" ] || (echo "Aborted." && exit 1); \
	fi
	$(COMPOSE_CMD) down --remove-orphans --volumes

config:
	@$(COMPOSE_CMD) config
