- name: Check if deploy dir is a git repo
  stat:
    path: "{{ deploy_dir }}/.git"
  register: git_repo

- name: Clone the repository
  command: git clone {{ repo_url }} {{ deploy_dir }}
  when: not git_repo.stat.exists

- name: Add deploy directory to git safe directories
  command: git config --global --add safe.directory {{ deploy_dir }}
