---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dhis2'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/api/metrics'
    basic_auth:
      # Username is hard coded since we can't use a secret here
      username: monitor
      password_file: /run/secrets/dhis2_monitor_password
