x-database-image: &database-image
  image: postgis/postgis:${POSTGRES_VERSION:-16-master}

x-file-storage-image: &file-storage-image
  image: rclone/rclone:${RCLONE_VERSION:-1.68}

services:
  backup-database:
    volumes:
      - ${BACKUP_DIR}:/backups
      - ./scripts/backup-database.sh:/backup-database.sh:ro
    environment:
      # -- Database hostname
      POSTGRES_HOST: database
      # -- Database username
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      # -- Database password
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      # -- Database name
      POSTGRES_DB: ${POSTGRES_DB:-dhis}
      # -- Database backup format
      POSTGRES_BACKUP_FORMAT: ${POSTGRES_BACKUP_FORMAT:-custom}
      # -- The `PGPASSWORD` environment variable is used by the `pg_dump` command`
      PGPASSWORD: ${POSTGRES_DB_PASSWORD}
    networks:
      - db
    entrypoint: [ "/bin/bash", "/backup-database.sh" ]
    <<: *database-image
    profiles:
      - backup

  backup-file-storage:
    volumes:
      - dhis2:/opt/dhis2:ro
      - ${BACKUP_DIR}:/backups
      - ./scripts/backup-file-storage.sh:/backup-file-storage.sh:ro
    environment:
      # -- Backup timestamp. Used to name the backup directory and the backup file. Since those are created by different containers, we need to ensure the backup timestamp is the same for both containers.
      BACKUP_TIMESTAMP: ${BACKUP_TIMESTAMP}
      # -- Directory to back up
      BACKUP_SOURCE_PATH: ${BACKUP_SOURCE_PATH:-/opt/dhis2/files}
    networks:
      - application
    entrypoint: [ "/bin/sh", "/backup-file-storage.sh" ]
    <<: *file-storage-image
    profiles:
      - backup

  restore-database:
    volumes:
      - ${BACKUP_DIR}:/backups:ro
      - ./scripts/restore-database.sh:/restore-database.sh:ro
      - ./scripts/fix-ownership.sh:/fix-ownership.sh:ro
    environment:
      # -- Database hostname
      POSTGRES_HOST: database
      # -- Database username
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      # -- Database password
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      # -- Database name
      POSTGRES_DB: ${POSTGRES_DB:-dhis}
      # -- The `PGPASSWORD` environment variable is used by the `pg_dump` command`
      PGPASSWORD: ${POSTGRES_PASSWORD}
      # -- Database restore file
      DB_RESTORE_FILE: ${DB_RESTORE_FILE}
      # -- Number of parallel jobs for pg_restore
      DB_RESTORE_NUMBER_OF_JOBS: ${DB_RESTORE_NUMBER_OF_JOBS:-4}
    networks:
      - db
    entrypoint: [ "/bin/bash", "/restore-database.sh" ]
    <<: *database-image
    profiles:
      - restore

  restore-file-storage:
    volumes:
      - dhis2:/opt/dhis2
      - ${BACKUP_DIR}:/backups:ro
      - ./scripts/restore-file-storage.sh:/restore-file-storage.sh:ro
    environment:
      # -- Directory to restore from
      FILE_STORAGE_RESTORE_SOURCE_DIR: ${FILE_STORAGE_RESTORE_SOURCE_DIR}
      # -- Directory to restore to
      RESTORE_DESTINATION_PATH: ${RESTORE_DESTINATION_PATH:-/opt/dhis2/files}
    networks:
      - application
    entrypoint: [ "/bin/sh", "/restore-file-storage.sh" ]
    <<: *file-storage-image
    profiles:
      - restore

networks:
  db:
    name: ${COMPOSE_PROJECT_NAME}-db
    external: true
