services:
  fill-storage:
    image: alpine:3.22
    volumes:
      - dhis2:/opt/dhis2:rw
      - ./scripts/fill-storage.sh:/fill-storage.sh:ro
    command: ["sh", "-c", "apk add --no-cache bash coreutils && /bin/bash /fill-storage.sh"]
    environment:
      TARGET_SIZE: 10737418240  # 10 * 1024 * 1024 * 1024 == 10 GB
      MIN_SIZE: 10240  # 10 * 1024 == 10 KB
      MAX_SIZE: 5242880  # 5 * 1024 * 1024 == 5 MB
      THREADS: 4
      CHUNK_SIZE: 2684354560  # TARGET_SIZE / THREADS
      OUTDIR: "/opt/dhis2/files/generated_files"
    depends_on:
      app:
        condition: service_healthy
