name: E2E Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Configure environment
        run: |
          ./scripts/generate-env.sh
          cat .env | sed '/^#/d' >> $GITHUB_ENV

          ./scripts/install-loki-driver.sh
        env:
          GEN_APP_HOSTNAME: dhis2-127-0-0-1.nip.io
          GEN_LETSENCRYPT_ACME_EMAIL: whatever@dhis2.org

      - name: E2e test
        run: |
          make playwright
          make test
